[project]
name = "robotbil"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "mpremote2>=1.22.1",
    "mpy-cross-v6-3>=1.1.1",
    "python-nmap>=0.7.1",
]
